### ISSUE TITLE
VSCode not launching after deactivation

### ISSUE THREAD

**Issue by ErickPetru** [syfxlin/vscode-acrylic#2]
Unfortunately, accidentally I clicked "Deactivate" just after installing the extension and then the VS Code crashed. Now, when I try to restart it, I get this error:

![image](https://user-images.githubusercontent.com/242274/65358839-0af53280-dbd1-11e9-8b6e-4b22765e0893.png)

What could I do about it?

**Comment by nsknsl** [comment]
same

**Comment by Erableto** [comment]
Same

**Comment by syfxlin** [comment]
Open the VSCode installation folder, which is usually in `C:\Users\you username\AppData\Local\Programs\Microsoft VS Code\resources\app\out`, There is a main.bak-acrylic file in the folder. Please check if the file content is empty. If it is not empty, rename it to main.js. Then open `C:\Users\you username\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-browser\workbench`, There is also a workbench.html.bak-acrylic here, rename it to workbench.html. If you do not see these two files, please reinstall VSCode.

**Comment by ErickPetru** [comment]
Hi @syfxlin, I couldn't try that steps, since I already reinstalled VS Code when the error occurred. But shouldn't the suggested steps be done automatically during the deactivation?

**Comment by syfxlin** [comment]
@ErickPetru Sorry, this is my negligence. Since I no longer use the acrylic effect, I will not update this plugin. You can achieve the same effect using [vscode-vibrancy](https://github.com/EYHN/vscode-vibrancy).

**Comment by ErickPetru** [comment]
Ok, thanks for the suggestion.
